name: Build CI

on:
  push:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]
  workflow_dispatch:

jobs:

  client-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up environment
        run: |
          echo "VITE_APP_API_URL=${{ secrets.APP_API_URL }}" >> .env
          echo "VITE_APP_RECAPTCHA_SITE_KEY=${{ secrets.APP_RECAPTCHA_SITE_KEY }}" >> .env
          echo "VITE_APP_SESSION=${{ secrets.APP_SESSION }}" >> .env
          echo "VITE_APP_NODE_ENV=${{ secrets.APP_NODE_ENV }}" >> .env
          echo "VITE_APP_SENTRY_DNS=${{ secrets.APP_SENTRY_DNS }}" >> .env
          echo "VITE_APP_GOOGLE_ANALYTICS=${{ secrets.APP_GOOGLE_ANALYTICS }}" >> .env
          echo "VITE_APP_GOOGLE_MAP=${{ secrets.APP_GOOGLE_MAP }}" >> .env
          echo "VITE_APP_GOOGLE_OAUTH_CLIENT_ID=${{ secrets.APP_GOOGLE_OAUTH_CLIENT_ID }}" >> .env
          echo "VITE_APP_GITHUB_OAUTH_CLIENT_ID=${{ secrets.APP_GITHUB_OAUTH_CLIENT_ID }}" >> .env
          echo "VITE_APP_FIREBASE_API_KEY=${{ secrets.APP_FIREBASE_API_KEY }}" >> .env
          echo "VITE_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_APP_FIREBASE_PROJECT_ID=${{ secrets.APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.APP_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_APP_FIREBASE_MESSAGING_SENDING_ID=${{ secrets.APP_FIREBASE_MESSAGING_SENDING_ID }}" >> .env
          echo "VITE_APP_FIREBASE_APP_ID=${{ secrets.APP_FIREBASE_APP_ID }}" >> .env
          echo "VITE_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.APP_FIREBASE_MEASUREMENT_ID }}" >> .env
          echo "VITE_APP_AWS_S3=${{ secrets.APP_AWS_S3 }}" >> .env
          echo "VITE_APP_MICROSOFT_OAUTH_CLIENT_ID=${{ secrets.APP_MICROSOFT_OAUTH_CLIENT_ID }}" >> .env

      - name: Install dependencies
        run: |
          npm ci

      - name: Executing lint test
        run: npm run pretty

      - name: Executing jest & mocha
        run: npm run test

      - name: Build frontend
        run: npm run build


  server-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 'latest'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 7

      - name: Set up environment
        run: |
          echo "MONGO_DB=core1" >> .env
          echo "MONGO_URL=mongodb://localhost:27017" >> .env
          echo "RECAPTCHA_SECRET=${{ secrets.EXPRESS_RECAPTCHA_SECRET }}" >> .env

      - name: Install dependencies
        run: |
          npm ci

      - name: Executing lint test
        run: npm run pretty

      - name: Executing jest & mocha
        run: npm run test
